addons:
  apt:
    packages:
      - texlive-latex-base
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-fonts-extra
      - texlive-latex-recommended
      - texlive-extra-utils
      - latex-xcolor
      - pgf

script:
  - for file in *.tex; do
      pdflatex -interaction=nonstopmode -halt-on-error $file;
    done

after_success:
- ./.travis_publish
